Repository seL4/seL4, pull requests merged in 2020-08, with the labels that each got.

#236 CI: Add a PR check to do a stand-alone kernel compilation
  .github/workflows/compilation-checks.yml
Labels: CI

#234 Check for reschedule on sched context return.
  include/object/notification.h
Labels: MCS

#241 manual: remove mention of system criticality
  manual/parts/threads.tex
Labels: docs
