Repository seL4/seL4, pull requests merged in 2021-08, with the labels that each got.

#482 fix up event trigger for hw build
  .github/workflows/sel4test-hw.yml
Labels: cleanup

#451 clarify that parameter is initial thread's region
  src/arch/riscv/kernel/boot.c
  src/arch/x86/kernel/boot.c
  src/kernel/boot.c
Labels: cleanup, proof-test, hw-test

#483 trivial: fix typos in comments
  include/arch/x86/arch/machine.h
Labels: docs

#486 github: enable hw test for imx8mm
  .github/workflows/sel4test-hw.yml
Labels: CI

#485 arm: flush cache to RAM on retype reset
  include/arch/arm/arch/machine.h
  src/arch/arm/32/kernel/vspace.c
  src/arch/arm/64/kernel/vspace.c
Labels: bug, verification, hw-test, security

#440 boot: make insert_region() static
  include/kernel/boot.h
  src/kernel/boot.c
Labels: enhancement, proof-test

#441 boot: use SEL4_PRIx_word instead of 'lx'
  src/kernel/boot.c
Labels: enhancement

#445 risc-v: add COMMON section to linker script
  CMakeLists.txt
  src/arch/arm/common_arm.lds
  src/arch/riscv/common_riscv.lds
  src/plat/pc99/linker.lds
Labels: enhancement

#491 github: deploy verification-manifest on preprocess
  .github/workflows/preprocess-deploy.yml
  README.md
Labels: CI

#475 ensure assert() macro is an atom
  include/assert.h
Labels: cleanup

#492 git hw test: enable zynqmp
  .github/workflows/sel4test-hw.yml
Labels: CI

#428 move scSporadic update in decodeSchedControl_ConfigureFlags
  src/object/schedcontrol.c
Labels: MCS

#496 mcs: sc_active not always true in sc_sporadic
  include/kernel/sporadic.h
Labels: MCS, hw-test

#461 risc-v: remove unused L2 cache functions
  include/arch/riscv/arch/machine.h
  src/arch/riscv/machine/hardware.c
Labels: cleanup, proof-test

#462 cleanup: Enforce ull for TIMER_FREQUENCY
  src/arch/arm/platform_gen.h.in
  src/arch/riscv/platform_gen.h.in
  src/drivers/timer/generic_timer.c
  src/plat/allwinnerA20/config.cmake
  src/plat/am335x/config.cmake
  src/plat/apq8064/config.cmake
  src/plat/ariane/config.cmake
  src/plat/bcm2711/config.cmake
  src/plat/bcm2837/config.cmake
  src/plat/exynos4/config.cmake
  src/plat/exynos5/config.cmake
  src/plat/fvp/config.cmake
  src/plat/hifive/config.cmake
  src/plat/hikey/config.cmake
  src/plat/imx31/config.cmake
  src/plat/imx6/config.cmake
  src/plat/imx7/config.cmake
  src/plat/imx8m-evk/config.cmake
  src/plat/odroidc2/config.cmake
  src/plat/odroidc4/config.cmake
  src/plat/omap3/config.cmake
  src/plat/polarfire/config.cmake
  src/plat/qemu-arm-virt/config.cmake
  src/plat/rocketchip/config.cmake
  src/plat/rockpro64/config.cmake
  src/plat/spike/config.cmake
  src/plat/tk1/config.cmake
  src/plat/tx1/config.cmake
  src/plat/tx2/config.cmake
  src/plat/zynq7000/config.cmake
  src/plat/zynqmp/config.cmake
Labels: cleanup

#467 mcs: Don't check if old SC is still configured
  src/kernel/thread.c
Labels: MCS, hw-build

#421 risc-v: don't add 8 bytes space at end of bss
  src/arch/riscv/common_riscv.lds
Labels: cleanup, hw-build

#505 mcs: Remove domain time check from preemptionPoint (v2)
  include/kernel/thread.h
  src/kernel/thread.c
Labels: MCS

#503 boot: reduce amount of helper functions
  include/arch/arm/arch/machine.h
  include/arch/riscv/arch/machine.h
  src/arch/arm/kernel/boot.c
  src/arch/arm/machine/hardware.c
  src/arch/riscv/kernel/boot.c
  src/arch/riscv/machine/hardware.c
Labels: cleanup

#501 use ARRAY_SIZE to avoid implicit assumptions
  src/kernel/boot.c
Labels: cleanup, proof-test

#438 boot: print reserved and available memory regions
  src/kernel/boot.c
Labels: enhancement

#525 trivial: use #ifdef instead of #if
  libsel4/sel4_plat_include/tqma8xqp1gb/sel4/plat/api/constants.h
Labels: hw-build

#526 aarch64: make gcc-10 happy
  CMakeLists.txt
Labels: hw-build
