Repository seL4/seL4, pull requests merged in 2021-05, with the labels that each got.

#267 mcs: cancel IPC when finalising reply caps
  src/object/objecttype.c
Labels: MCS, verification

#360 Add MCS to the preprocess check
  .github/workflows/pr.yml
Labels: CI

#202 arm-hyp: read cntv_ctl from saved context when necessary
  include/arch/arm/armv/armv8-a/64/armv/vcpu.h
Labels: virtualisation

#310 arm: fix `decodeARMMMUInvocation` branch hint
  src/arch/arm/32/kernel/vspace.c
  src/arch/arm/64/kernel/vspace.c
Labels: verification
