Repository seL4/seL4, pull requests merged in 2021-06, with the labels that each got.

#376 Set KernelPaddrUserTop correctly on ARM platforms
  src/arch/arm/config.cmake
Labels: bug

#375 Add support for iMX LP UART
  src/drivers/serial/config.cmake
  src/drivers/serial/imx-lpuart.c
  tools/hardware.yml
Labels: enhancement

#396 github: add a GitHub action to build the manual
  .github/workflows/manual.yml
Labels: CI, docs

#401 use '#pragma once' include guards
  tools/hardware/outputs/c_header.py
Labels: enhancement

#412 github: CI action to lint seL4 IDL files
  .github/workflows/xml_lint.yml
Labels: CI

#423 github: run C parser on push/PR
  .github/workflows/cparser.yml
Labels: CI
