Repository seL4/seL4, pull requests merged in 2021-11, with the labels that each got.

#628 Custom DTS overlay file support
  config.cmake
Labels: enhancement

#601 Add missing include and improve comments
  include/util.h
Labels: docs, cleanup

#643 remove unused define KERNEL_ELF_PADDR_TOP
  include/hardware.h
Labels: cleanup

#650 trivial: fix grammar in comment
  src/arch/riscv/kernel/vspace.c
Labels: docs

#654 generate test hardware matrix
  .github/workflows/sel4test-deploy.yml
  .github/workflows/sel4test-hw.yml
Labels: CI

#624 rpi4: Add UART DTS support
  src/plat/bcm2711/config.cmake
  src/plat/bcm2711/overlay-rpi4-address-mapping.dts
Labels: hw-build

#659 print 64-bit integers on 32-bits systems fully
  include/stdint.h
  src/machine/io.c
Labels: enhancement

#666 cmake: fix typo
  config.cmake
  include/arch/riscv/arch/32/mode/hardware.h
  include/util.h
  src/kernel/boot.c
Labels: docs

#668 remove obsolete define HAVE_AUTOCONF
  CHANGES
  CMakeLists.txt
Labels: cleanup

#645 consolidate arm core specific constants
  libsel4/arch_include/arm/sel4/arch/constants_cortex_a15.h
  libsel4/arch_include/arm/sel4/arch/constants_cortex_a35.h
  libsel4/arch_include/arm/sel4/arch/constants_cortex_a53.h
  libsel4/arch_include/arm/sel4/arch/constants_cortex_a55.h
  libsel4/arch_include/arm/sel4/arch/constants_cortex_a57.h
  libsel4/arch_include/arm/sel4/arch/constants_cortex_a7.h
  libsel4/arch_include/arm/sel4/arch/constants_cortex_a72.h
  libsel4/arch_include/arm/sel4/arch/constants_cortex_a8.h
  libsel4/arch_include/arm/sel4/arch/constants_cortex_a9.h
  libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/constants.h
  libsel4/sel4_arch_include/aarch64/sel4/sel4_arch/constants.h
  libsel4/sel4_plat_include/allwinnerA20/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/am335x/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/apq8064/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/bcm2711/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/bcm2837/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/exynos4/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/exynos5/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/fvp/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/hikey/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/imx6/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/imx7/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/imx8mm-evk/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/imx8mq-evk/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/odroidc2/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/odroidc4/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/omap3/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/qemu-arm-virt/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/rockpro64/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/tk1/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/tqma8xqp1gb/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/tx1/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/tx2/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/zynq7000/sel4/plat/api/constants.h
  libsel4/sel4_plat_include/zynqmp/sel4/plat/api/constants.h
Labels: cleanup, hw-test

#674 align include guards for seL4_DebugSendIPI()
  libsel4/arch_include/arm/sel4/arch/syscalls.h
  libsel4/include/api/syscall.xml
Labels: cleanup
