Repository seL4/seL4, pull requests merged in 2021-04, with the labels that each got.

#335 Move null check to start of schedcontext decode
  src/object/schedcontext.c
Labels: MCS, verification

#342 mcs: Fix conversion of ticks to us on aarch64
  include/arch/arm/arch/64/mode/machine/timer.h
Labels: MCS

#339 mcs: removed donator from release queue
  src/object/schedcontext.c
Labels: MCS, verification

#263 Fix MCS/SMP refill_order assertion
  src/kernel/sporadic.c
Labels: MCS, SMP

#341 mcs: move maybeReturnSc to end of receiveSignal
  src/object/notification.c
Labels: MCS, verification

#329 mcs: Only unbind extant donated ntfn sc
  include/object/notification.h
Labels: MCS

#338 Current thread must not yield to multiple threads
  src/object/schedcontext.c
Labels: MCS, verification
