Repository seL4/seL4, pull requests merged in 2021-07, with the labels that each got.

#420 boot: make linker definitions generic
  include/hardware.h
  src/arch/arm/kernel/boot.c
  src/arch/riscv/kernel/boot.c
  src/arch/x86/kernel/boot_sys.c
Labels: enhancement

#419 debug: always print TIMER_CLOCK_HZ as a uint64
  src/drivers/timer/generic_timer.c
Labels: enhancement

#379 add disabled config options as comments in the generated header files
  tools/helpers.cmake
Labels: enhancement

#444 Add GitHub action for sel4test simulation runs
  .github/workflows/sel4test-sim.yml
Labels: CI

#400 Set KernelPaddrUserTop correctly on RISC-V platforms
  src/arch/riscv/config.cmake
Labels: bug

#429 risc-v/boot: verbosely log boot errors
  src/arch/arm/kernel/boot.c
  src/arch/riscv/kernel/boot.c
Labels: enhancement

#457 C proof check for labelled PR
  .github/workflows/proof.yml
Labels: CI

#459 github: run SimplExportAndRefine conditionally
  .github/workflows/proof.yml
Labels: CI

#450 remove redundant defines
  include/kernel/boot.h
Labels: cleanup

#458 README: add badge for simulation test
  README.md
Labels: CI, docs

#404 hardware_gen.py: Address some warning messages
  tools/hardware.yml
  tools/hardware/outputs/c_header.py
Labels: hw-build

#437 boot: move create_untypeds() to generic code
  include/kernel/boot.h
  src/arch/arm/kernel/boot.c
  src/arch/riscv/kernel/boot.c
  src/arch/x86/kernel/boot.c
  src/kernel/boot.c
Labels: hw-build, proof-test
