Repository seL4/seL4, pull requests merged in 2021-09, with the labels that each got.

#516 boot: remove ndks_boot.slot_pos_max
  include/kernel/boot.h
  src/kernel/boot.c
Labels: cleanup

#533 cleanup code using BI_PTR(), use BI_FRAME_SIZE_BITS instead of seL4_PageBits
  include/bootinfo.h
  src/kernel/boot.c
Labels: cleanup

#546 Add additional cmake checks
  configs/seL4Config.cmake
Labels: enhancement

#554 risc-v: fix signature for Arch_setTLSRegister()
  include/arch/riscv/arch/machine.h
Labels: bug, proof-test

#551 boot: improve user image location check
  src/arch/arm/kernel/boot.c
  src/arch/riscv/kernel/boot.c
Labels: cleanup

#555 risc-v: add comment about SBI constants
  include/arch/riscv/arch/sbi.h
Labels: docs

#553 boot: assert() on RISC-V also if insert_region() fails
  src/kernel/boot.c
Labels: cleanup

#563 github: drop python2 tests
  .github/workflows/compilation-checks.yml
Labels: CI

#433 boot/risc-v: grab BKL on primary core for SMP
  src/arch/arm/kernel/boot.c
  src/arch/riscv/kernel/boot.c
Labels: enhancement, SMP, hw-build

#570 trivial: formatting, improve comments about interrupt handling
  src/object/interrupt.c
Labels: docs

#544 Ensure execute_process is error checked
  config.cmake
  src/plat/qemu-arm-virt/config.cmake
Labels: bug

#545 Remove unused PYTHON tool definition
  CMakeLists.txt
Labels: cleanup

#577 boot: change order to improve debug output
  src/kernel/boot.c
Labels: cleanup, hw-test

#581 boot: simplify create_untypeds_for_region()
  src/kernel/boot.c
Labels: cleanup

#585 remove goto in printf_core() and return directly
  src/machine/io.c
Labels: cleanup

#587 boot: handle failure to find root server memory
  src/kernel/boot.c
Labels: bug, proof-test

#593 python: raise exceptions on errors
  tools/hardware/memory.py
Labels: enhancement

#592 python: add __str__() for Region
  tools/hardware/memory.py
Labels: cleanup

#596 move type checks to mode/types.h
  include/arch/arm/arch/32/mode/types.h
  include/arch/arm/arch/64/mode/types.h
  include/arch/arm/arch/types.h
  include/arch/x86/arch/32/mode/types.h
  include/arch/x86/arch/64/mode/types.h
  include/arch/x86/arch/types.h
Labels: cleanup

#594 boot: remove redundancy in assignments
  src/arch/arm/kernel/boot.c
  src/arch/riscv/kernel/boot.c
Labels: cleanup, proof-test

#597 boot: remove unnecessary cast
  src/arch/riscv/kernel/boot.c
Labels: cleanup, proof-test

#603 cmake/rockpro64: remove unnecessary configuration
  src/plat/rockpro64/config.cmake
Labels: cleanup, hw-build
