Repository seL4/seL4, pull requests merged in 2021-12, with the labels that each got.

#675 riscv: add missing benchmark function
  include/arch/riscv/arch/benchmark.h
Labels: cleanup

#673 avoid invoking scheduler when setting log buffer
  src/api/syscall.c
Labels: cleanup

#681 riscv: use wrapper function
  src/arch/riscv/smp/ipi.c
Labels: cleanup

#680 riscv: pass hart mask by value to SBI wrappers
  include/arch/riscv/arch/machine.h
  include/arch/riscv/arch/sbi.h
  src/arch/riscv/smp/ipi.c
Labels: cleanup, proof-test

#679 Fix getMaxUsToTicks function in RISC-V machine/timer.h
  include/arch/riscv/arch/machine/timer.h
Labels: bug, proof-test

#642 python: use KernelSel4Arch instead of KernelArch
  config.cmake
  tools/hardware/config.py
  tools/hardware/outputs/c_header.py
  tools/hardware_gen.py
Labels: hw-build

#367 Fix d-cache flush on aarch32
  include/arch/arm/arch/32/mode/machine.h
Labels: hw-test

#321 trivial: Make the branch easier to understand.
  src/kernel/cspace.c
Labels: verification

#595 unify libsel4 type definitions
  include/arch/arm/arch/types.h
  include/arch/riscv/arch/types.h
  include/arch/x86/arch/types.h
  include/basic_types.h
Labels: cleanup, hw-build

#694 trivial: fix typo in comment
  src/arch/arm/kernel/boot.c
Labels: docs

#689 trivial: remove semicolon after macro
  src/arch/arm/machine/gic_v2.c
Labels: cleanup, proof-test

#698 libsel4: adjust asm immediate syntax for clang
  libsel4/sel4_arch_include/aarch32/sel4/sel4_arch/syscalls.h
Labels: proof-test, hw-test

#702 trivial: fix typos in comment
  src/arch/arm/kernel/boot.c
Labels: docs, hw-test

#706 boot/risc-v: add missing include
  src/arch/riscv/kernel/boot.c
Labels: cleanup

#704 boot/risc-v: pv_offset cannot be uint32_t
  src/arch/riscv/kernel/boot.c
Labels: bug

#712 boot: check index before accessing element
  src/kernel/boot.c
Labels: bug, proof-test

#713 Add numDomains enumeration constant
  include/api/types.h
  include/kernel/thread.h
  src/kernel/thread.c
  src/object/tcb.c
Labels: verification

#718 trivial: remove whitespace
  include/api/failures.h
Labels: cleanup
