Repository seL4/seL4, pull requests merged in 2022-03, with the labels that each got.

#790 Add call to vcpu_switch to associateVCPUTCB
  src/arch/arm/object/vcpu.c
Labels: verification, virtualisation, hw-test

#785 benchmark/trace: remove conditional else block
  src/arch/x86/machine/breakpoint.c
Labels: cleanup

#799 bitfield_gen: allow non-contiguous tag fields
  tools/bitfield_gen.py
Labels: hw-build

#802 cmake: remove unused code
  config.cmake
Labels: hw-build

#808 python: use '#paragma once' include guard
  libsel4/tools/syscall_stub_gen.py
  tools/bitfield_gen.py
  tools/invocation_header_gen.py
Labels: cleanup
