Repository seL4/seL4, pull requests merged in 2022-07, with the labels that each got.

#880 RISC-V PTE compliance.
  src/arch/riscv/kernel/vspace.c
Labels: verification

#882 Small common_riscv.lds improvements
  src/arch/arm/common_arm.lds
  src/arch/riscv/common_riscv.lds
Labels: hw-test

#885 structures: fix MCS 64-bit notification obj size
  include/object/structures.h
  include/object/structures_64.bf
Labels: MCS, hw-build
