Repository seL4/seL4, pull requests merged in 2022-09, with the labels that each got.

#906 mcs: remove unused tcbReply field from tcb struct
  include/object/structures.h
Labels: MCS, proof-test

#911 aarch64: Use isb after changing FPU control registers
  include/arch/arm/arch/64/mode/machine/fpu.h
Labels: verification, hw-test

#923 cmake: add a sanity check
  configs/seL4Config.cmake
Labels: build-system

#917 remove redundant definitions
  src/machine/capdl.c
Labels: cleanup
