Repository seL4/seL4, pull requests merged in 2022-06, with the labels that each got.

#858 cmake: support for supplying custom device trees
  config.cmake
Labels: build-system

#866 tools/bitfield_gen: ensure UTF-8 encoding
  tools/bitfield_gen.py
  tools/umm.py
Labels: hw-build, build-system

#846 Don't clobber msgInfo register after an invocation
  include/arch/arm/arch/kernel/vspace.h
  include/arch/riscv/arch/kernel/vspace.h
  include/arch/x86/arch/kernel/vspace.h
  include/arch/x86/arch/object/objecttype.h
  include/arch/x86/arch/object/vcpu.h
  src/arch/arm/32/kernel/vspace.c
  src/arch/arm/32/object/objecttype.c
  src/arch/arm/64/kernel/vspace.c
  src/arch/arm/64/object/objecttype.c
  src/arch/arm/object/smmu.c
  src/arch/riscv/kernel/vspace.c
  src/arch/riscv/object/objecttype.c
  src/arch/x86/32/kernel/vspace.c
  src/arch/x86/32/kernel/vspace_32paging.c
  src/arch/x86/32/object/objecttype.c
  src/arch/x86/64/kernel/vspace.c
  src/arch/x86/64/object/objecttype.c
  src/arch/x86/kernel/vspace.c
  src/arch/x86/object/ioport.c
  src/arch/x86/object/objecttype.c
  src/arch/x86/object/vcpu.c
  src/object/tcb.c
Labels: verification

#872 mcs: add AUXUPD and GHOSTUPD comments for verification
  src/object/objecttype.c
Labels: MCS
