Repository seL4/seL4, pull requests merged in 2022-02, with the labels that each got.

#758 github: let hw test run to completion on failure
  .github/workflows/sel4test-deploy.yml
Labels: CI

#762 github: add AARCH64 to preprocess test
  .github/workflows/pr.yml
  .github/workflows/preprocess-deploy.yml
Labels: CI

#765 github: standalone-compilation for AARCH64
  .github/workflows/compilation-checks.yml
Labels: CI

#764 aarch64: verification VCPU tweaks
  include/arch/arm/armv/armv8-a/64/armv/vcpu.h
Labels: verification, hw-test

#733 Add support for generating syscall_stubs for different languages
  libsel4/tools/syscall_stub_gen_rs.py
Labels: enhancement

#768 github: trigger xml-lint test on dtd changes
  .github/workflows/xml_lint.yml
Labels: CI

#778 trivial: Convert UTF-8 character to ASCII
  include/util.h
  src/machine/io.c
Labels: docs

#777 doc: update comment about mask
  src/kernel/cspace.c
Labels: docs

#782 use unreachable instead of returning something
  src/kernel/cspace.c
Labels: proof-test
