Repository seL4/seL4, pull requests merged in 2022-01, with the labels that each got.

#730 risc-v: remove misleading comment
  src/arch/riscv/common_riscv.lds
Labels: docs

#723 manual: fix typo, improve readability
  manual/parts/bootup.tex
Labels: docs

#725 remove obsolete prototype
  include/arch/arm/arch/kernel/vspace.h
Labels: cleanup

#735 cleanup templates for generated code
  tools/syscall_header_gen.py
Labels: cleanup

#726 add missing config.h include
  include/arch/riscv/arch/kernel/vspace.h
  include/kernel/boot.h
Labels: cleanup

#739 keep seL4_Word for seL4_BootInfoID
  libsel4/include/sel4/bootinfo_types.h
Labels: verification

#740 trivial: fix typo in comment
  src/arch/x86/c_traps.c
Labels: docs

#715 a bit of code cleanup
  src/kernel/boot.c
Labels: cleanup, proof-test

#741 github: proof test only for most recent push
  .github/workflows/proof.yml
Labels: CI

#746 config: AARCH64 config for verification
  configs/AARCH64_verified.cmake
Labels: verification

#708 trivial: add comment about RISC-V ZiHintPause
  include/arch/riscv/arch/machine.h
Labels: docs

#662 cmake: cleanup compiler and linker flag setup
  CMakeLists.txt
Labels: hw-build

#699 boot: don't round DTB area down or up
  src/arch/arm/kernel/boot.c
  src/arch/riscv/kernel/boot.c
Labels: proof-test

#646 RISC-V: align with ARM, move rv32 CSR access wrappers
  include/arch/riscv/arch/32/mode/hardware.h
  include/arch/riscv/arch/32/mode/machine.h
  include/arch/riscv/arch/64/mode/hardware.h
  include/arch/riscv/arch/64/mode/machine.h
Labels: cleanup, proof-test
