Repository seL4/seL4, pull requests merged in 2022-05, with the labels that each got.

#834 benchmark/arm64: write-through kernel log buffer
  src/arch/arm/64/kernel/vspace.c
Labels: verification

#845 github: switch proofs to Isabelle2021-1
  .github/workflows/proof.yml
Labels: CI

#843 x86_64: Fix x86_64 gcc compile error with sysexitq
  include/arch/x86/arch/64/mode/fastpath/fastpath.h
  include/arch/x86/arch/64/mode/machine.h
  src/arch/x86/64/c_traps.c
Labels: proof-test

#822 risc-v: add SBI remote hart mask helper function
  include/arch/riscv/arch/machine.h
Labels: cleanup

#851 trivial: add missing space character
  include/arch/riscv/arch/machine.h
Labels: hw-build

#852 Remove redundant sc_active checks
  src/kernel/thread.c
  src/object/notification.c
Labels: verification, MCS
