Repository seL4/seL4, pull requests merged in 2022-10, with the labels that each got.

#919 make macro less obscure
  include/kernel/boot.h
Labels: cleanup

#937 zynqmp: remove hypervisor overlay
  src/plat/zynqmp/config.cmake
  src/plat/zynqmp/overlay-hs-zynqmp.dts
Labels: hw-test

#939 mcs: modify GHOST_UPD comment for verification
  src/object/objecttype.c
Labels: MCS

#931 fastpatch: use thread passed as parameter
  include/arch/arm/arch/32/mode/fastpath/fastpath.h
  include/arch/arm/arch/64/mode/fastpath/fastpath.h
  include/arch/riscv/arch/fastpath/fastpath.h
Labels: cleanup

#921 boot: remove unused return values
  include/kernel/boot.h
  src/arch/arm/kernel/boot.c
  src/arch/riscv/kernel/boot.c
  src/arch/x86/kernel/boot.c
  src/kernel/boot.c
Labels: cleanup
