Repository seL4/seL4, pull requests merged in 2022-11, with the labels that each got.

#938 mcs: correct MinSchedContextBits and add compile assert
  libsel4/include/sel4/constants.h
Labels: MCS, hw-build

#950 github: enable sel4bench hardware test on PR
  .github/workflows/sel4bench-pr.yml
Labels: CI

#727 Add Quartz64 support
  libsel4/sel4_plat_include/quartz64/sel4/plat/api/constants.h
  src/plat/quartz64/config.cmake
  src/plat/quartz64/overlay-quartz64.dts
  tools/dts/quartz64.dts
  tools/dts/update-dts.sh
Labels: new-platform
