Repository seL4/seL4, pull requests merged in 2023-08, with the labels that each got.

#1080 Fix typo in comment for KernelDomainSchedule config option
  config.cmake
Labels: docs

#1082 manual: fix typos in x86 virtualisation section
  manual/parts/threads.tex
Labels: docs

#1061 Output JSON for hardware configuration
  CMakeLists.txt
  config.cmake
  tools/hardware/outputs/json.py
  tools/hardware_gen.py
Labels: enhancement

#1076 Read timestamp directly from CLINT for RISC-V platforms
  CHANGES
  include/arch/riscv/arch/32/mode/machine.h
  include/arch/riscv/arch/64/mode/machine.h
  src/arch/riscv/config.cmake
  src/plat/ariane/config.cmake
  src/plat/hifive/config.cmake
  src/plat/polarfire/config.cmake
  src/plat/qemu-riscv-virt/config.cmake
  src/plat/rocketchip/config.cmake
  src/plat/spike/config.cmake
Labels: proof-test, hw-test, hw-bench

#652 boot: simplify boot code recycling
  include/arch/x86/arch/kernel/boot.h
  include/hardware.h
  include/kernel/boot.h
  src/arch/arm/kernel/boot.c
  src/arch/riscv/kernel/boot.c
  src/arch/x86/kernel/boot.c
  src/arch/x86/kernel/boot_sys.c
  src/kernel/boot.c
Labels: cleanup

#1066 manual: improve thread affinity description
  manual/parts/threads.tex
Labels: docs

#707 boot: sanity check for SMP lock variable state
  src/arch/arm/kernel/boot.c
  src/arch/riscv/kernel/boot.c
Labels: docs, cleanup
