Repository seL4/seL4, pull requests merged in 2023-03, with the labels that each got.

#980 Include change to MinSchedContextBits in CHANGES
  CHANGES
Labels: docs

#984 ci proof: Upload build artifacts
  .github/workflows/proof.yml
Labels: CI

#982 configs: Ensure compatibility with binary verification
  configs/ARM_MCS_verified.cmake
  configs/ARM_verified.cmake
  configs/RISCV64_MCS_verified.cmake
  configs/RISCV64_verified.cmake
Labels: verification, CI, proof-test

#985 cmake: mention gen_config.h change in CHANGES
  CHANGES
Labels: docs

#983 make physBase a static inline function
  include/arch/arm/arch/32/mode/hardware.h
  include/arch/arm/arch/64/mode/hardware.h
  include/arch/riscv/arch/32/mode/hardware.h
  include/arch/riscv/arch/64/mode/hardware.h
  include/plat/pc99/plat/32/plat_mode/machine/hardware.h
  include/plat/pc99/plat/64/plat_mode/machine/hardware.h
  src/arch/arm/32/kernel/vspace.c
  src/arch/arm/common_arm.lds
  src/arch/riscv/common_riscv.lds
  src/plat/pc99/linker.lds
  tools/hardware/outputs/c_header.py
Labels: verification

#744 VM fault fastpath
  config.cmake
  include/arch/arm/arch/64/mode/fastpath/fastpath.h
  include/arch/arm/arch/64/mode/kernel/vspace.h
  include/arch/arm/arch/fastpath/fastpath.h
  include/fastpath/fastpath.h
  src/arch/arm/64/kernel/vspace.c
  src/arch/arm/c_traps.c
  src/fastpath/fastpath.c
Labels: hw-build, hw-test

#988 x86,boot: Round normal memory regions to 4k align
  src/arch/x86/kernel/boot_sys.c
Labels: hw-build, hw-test

#992 remove unused argument from mcsPreemptionPoint
  src/api/syscall.c
Labels: verification, MCS, cleanup

#993 Move getActiveIRQ() close to use site
  src/api/syscall.c
Labels: verification, MCS, cleanup, proof-test

#994 manual: improvements to VSpace section
  manual/parts/vspace.tex
Labels: docs
