Repository seL4/seL4, pull requests merged in 2023-10, with the labels that each got.

#1113 github: bump Isabelle version on proof checks
  .github/workflows/proof.yml
Labels: CI

#1112 arm: tune vcpu/gic struct padding for verification
  include/arch/arm/arch/object/vcpu.h
Labels: hw-test

#1115 mcs: rephrase refill_capacity to ease verification
  include/kernel/sporadic.h
Labels: verification, MCS, hw-build

#1117 github: add MCS C proofs to proof check
  .github/workflows/proof.yml
Labels: CI

#1118 aarch64: make error reporting consistent
  src/arch/arm/64/kernel/vspace.c
Labels: cleanup

#1114 ARM: No special handling for edge-triggered IRQs
  include/arch/arm/arch/machine/gic_v2.h
  include/arch/arm/arch/machine/gic_v3.h
Labels: performance

#1121 aarch64: use VS prefix for vspace_cap fields
  include/arch/arm/arch/64/mode/fastpath/fastpath.h
  include/arch/arm/arch/64/mode/kernel/vspace.h
  include/arch/arm/arch/64/mode/object/structures.bf
  include/arch/arm/arch/64/mode/object/structures.h
  src/arch/arm/64/kernel/vspace.c
  src/arch/arm/64/machine/capdl.c
  src/arch/arm/64/object/objecttype.c
  src/arch/arm/object/smmu.c
  src/fastpath/fastpath.c
Labels: cleanup

#1122 github: fix sel4bench trigger in GitHub workflow
  .github/workflows/sel4bench-pr.yml
Labels: CI
