Repository seL4/seL4, pull requests merged in 2023-04, with the labels that each got.

#1010 bitfield_gen: comment for original source file
  CMakeLists.txt
  libsel4/CMakeLists.txt
  tools/bitfield_gen.py
  tools/helpers.cmake
Labels: docs, build-system

#1013 boot: add missing line break in error messages
  src/arch/arm/kernel/boot.c
  src/kernel/boot.c
Labels: cleanup

#1021 gcc.cmake: add more known ARM cross compilers
  gcc.cmake
Labels: build-system

#1014 ipi: add missing barrier and enforce completion
  include/arch/arm/arch/machine/hardware.h
  include/arch/arm/armv/armv7-a/armv/machine.h
  include/arch/arm/armv/armv8-a/64/armv/machine.h
  src/smp/ipi.c
Labels: hw-build

#1028 gic_v3: use CNTPCT instead of CNTFRQ
  src/arch/arm/machine/gic_v3.c
Labels: hw-build
