Repository seL4/seL4, pull requests merged in 2023-11, with the labels that each got.

#1092 riscv: place traps and fastpath code adjacently
  include/arch/riscv/arch/kernel/traps.h
  src/arch/riscv/common_riscv.lds
  src/arch/riscv/traps.S
Labels: proof-test, hw-bench

#1129 remove useless assert
  src/kernel/thread.c
Labels: cleanup

#1134 MCS: tweak validFaultHandler and installTCBCap for verification
  src/object/tcb.c
Labels: MCS

#1133 exynos4: remove explicit setting of TIMER_PRECISION
  src/plat/exynos4/config.cmake
Labels: cleanup

#824 cmake: extend macro declare_seL4_arch() to support multiple architectures
  configs/seL4Config.cmake
  src/plat/bcm2711/config.cmake
  src/plat/bcm2837/config.cmake
  src/plat/exynos5/config.cmake
  src/plat/hikey/config.cmake
  src/plat/imx8m-evk/config.cmake
  src/plat/maaxboard/config.cmake
  src/plat/pc99/config.cmake
  src/plat/qemu-arm-virt/config.cmake
  src/plat/qemu-riscv-virt/config.cmake
  src/plat/spike/config.cmake
  src/plat/tk1/config.cmake
  src/plat/zynqmp/config.cmake
Labels: hw-build, build-system

#1142 CMake: show DTS name in error message
  config.cmake
Labels: build-system
