Repository seL4/seL4, pull requests merged in 2023-01, with the labels that each got.

#958 mcs: remove redundant memzero from createObject
  src/object/objecttype.c
Labels: MCS, hw-test

#793 Signal fastpath v2
  config.cmake
  include/arch/arm/arch/fastpath/fastpath.h
  include/arch/arm/arch/kernel/traps.h
  include/fastpath/fastpath.h
  include/object/endpoint.h
  include/object/notification.h
  src/arch/arm/64/traps.S
  src/arch/arm/c_traps.c
  src/fastpath/fastpath.c
  src/object/endpoint.c
  src/object/notification.c
Labels: MCS

#932 user proper field from thread context structure
  include/arch/arm/arch/32/mode/fastpath/fastpath.h
  include/arch/riscv/arch/fastpath/fastpath.h
Labels: cleanup, hw-test

#963 libsel4: use `LIBSEL4_INLINE_FUNC` attributes for `seL4_NBWait`
  libsel4/sel4_arch_include/x86_64/sel4/sel4_arch/syscalls.h
Labels: cleanup

#962 mcs: update AUXUPD comment for verification
  src/object/objecttype.c
Labels: MCS
