Repository seL4/seL4, pull requests merged in 2024-06, with the labels that each got.

#896 Only access IOAPIC registers that are actually present
  src/plat/pc99/machine/ioapic.c
Labels: verification

#1249 Add new imx8mp-evk platform
  libsel4/sel4_plat_include/imx8mp-evk/sel4/plat/api/constants.h
  src/plat/imx8m-evk/config.cmake
  src/plat/imx8m-evk/overlay-imx8mp-evk.dts
  tools/dts/imx8mp-evk.dts
Labels: hw-build, new-platform

#1264 github: use default Isabelle version for proofs
  .github/workflows/proof.yml
Labels: CI

#1263 ioapic: set IOAPIC_IRQ_LINES to max allowed
  include/plat/pc99/plat/machine.h
  src/plat/pc99/machine/ioapic.c
Labels: hw-test

#1262 mcs: refactor refill_unblock_check to ease verification
  src/kernel/sporadic.c
Labels: verification, MCS

#1255 Review of user manual (only typos and syntax)
  libsel4/arch_include/arm/interfaces/sel4arch.xml
  libsel4/arch_include/riscv/interfaces/sel4arch.xml
  libsel4/arch_include/x86/interfaces/sel4arch.xml
  libsel4/include/interfaces/sel4.xml
  libsel4/include/sel4/syscalls.h
  libsel4/include/sel4/syscalls_master.h
  libsel4/include/sel4/syscalls_mcs.h
  libsel4/sel4_arch_include/aarch64/interfaces/sel4arch.xml
  manual/parts/cspace.tex
  manual/parts/glossary.tex
  manual/parts/io.tex
  manual/parts/ipc.tex
  manual/parts/objects.tex
  manual/parts/threads.tex
  manual/parts/vspace.tex
Labels: docs

#1251 vcpu: only trap WFx instructions from vCPUs
  include/arch/arm/armv/armv7-a/armv/vcpu.h
  include/arch/arm/armv/armv8-a/64/armv/vcpu.h
Labels: verification

#1266 mcs: rewrite guard in preemptionPoint
  src/model/preemption.c
Labels: MCS

#1269 mcs: use sc_active in isSchedulable
  include/kernel/thread.h
Labels: MCS

#1278 config.py: fix SUPERSECTION_BITS for arm_hyp
  tools/hardware/config.py
Labels: build-system
