Repository seL4/seL4, pull requests merged in 2024-10, with the labels that each got.

#1315 aarch32: remove unused functions
  include/arch/arm/arch/32/mode/machine.h
  include/arch/arm/arch/32/mode/machine_pl2.h
Labels: hw-build

#1329 mcs: use sc_active in commitTime
  include/kernel/thread.h
Labels: MCS

#1302 mcs: refactor cancelAllIPC and cancelBadgedSends
  src/object/endpoint.c
Labels: MCS

#1289 move cache flush from untyped reset to retype
  include/arch/arm/arch/machine.h
  include/arch/riscv/arch/machine.h
  include/arch/x86/arch/machine.h
  src/arch/arm/32/object/objecttype.c
  src/arch/arm/64/object/objecttype.c
Labels: verification
