Repository seL4/seL4, pull requests merged in 2024-01, with the labels that each got.

#1153 python: remove unused template parameter
  tools/invocation_header_gen.py
Labels: cleanup, hw-build

#1159 CI: update deploy workflow also
  .github/workflows/sel4test-deploy.yml
Labels: CI

#1161 aarch64/vspace: avoid unnecessary casts
  src/arch/arm/64/kernel/vspace.c
Labels: verification

#1165 aarch64/vspace: adjust type for verification
  src/arch/arm/64/kernel/vspace.c
Labels: verification

#1144 make method names consistent
  libsel4/arch_include/arm/interfaces/sel4arch.xml
  libsel4/arch_include/riscv/interfaces/sel4arch.xml
  libsel4/arch_include/x86/interfaces/sel4arch.xml
  libsel4/include/interfaces/sel4.xml
  libsel4/include/sel4/syscalls.h
  libsel4/include/sel4/syscalls_master.h
  libsel4/include/sel4/syscalls_mcs.h
  libsel4/sel4_arch_include/x86_64/interfaces/sel4arch.xml
Labels: docs

#1166 manual: add bibliography to toc
  manual/manual.tex
Labels: docs

#1162 Hardware Debug API: Single stepping on ARMv7
  src/arch/arm/machine/debug.c
Labels: hw-test, debug-build

#1168 aarch64/vspace: test for page type directly
  src/arch/arm/64/kernel/vspace.c
Labels: verification

#1152 cmake: propagate `CROSS_COMPILER_PREFIX`
  gcc.cmake
Labels: build-system

#1169 aarch64/vspace: fix error reporting in decode
  src/arch/arm/64/kernel/vspace.c
Labels: verification

#1172 github: bump GitHub actions to node20
  .github/workflows/compilation-checks.yml
  .github/workflows/manual.yml
  .github/workflows/proof.yml
  .github/workflows/sel4bench-pr.yml
  .github/workflows/sel4test-deploy.yml
  .github/workflows/sel4test-hw.yml
  .github/workflows/xml_lint.yml
Labels: CI

#1171 aarch64/vspace: type of counter in ASIDPoolAssign
  src/arch/arm/64/kernel/vspace.c
Labels: verification

#1177 CI: the seL4/machine_queue repo is public now
  .github/workflows/sel4bench-pr.yml
  .github/workflows/sel4test-deploy.yml
  .github/workflows/sel4test-hw.yml
Labels: CI

#1178 CI: cancel older concurrent PR runs
  .github/workflows/sel4bench-pr.yml
  .github/workflows/sel4test-hw.yml
  .github/workflows/sel4test-sim.yml
Labels: CI
