Repository seL4/seL4, pull requests merged in 2024-02, with the labels that each got.

#1180 AArch64: mark isFpuEnable as DONT_TRANSLATE
  include/arch/arm/arch/64/mode/machine/fpu.h
Labels: verification

#1182 Fix QEMU/arm CPU selection
  src/plat/qemu-arm-virt/config.cmake
Labels: bug, build-system

#1184 cmake: Support multiple overlay files
  config.cmake
Labels: build-system

#1106 cmake: Install object API files under better names
  CMakeLists.txt
Labels: build-system

#1190 github: disambiguate proof artifact upload
  .github/workflows/proof.yml
Labels: CI

#1047 elfloader: Replace calls to reset_cntvoff
  src/plat/bcm2711/overlay-rpi4.dts
  src/plat/bcm2837/overlay-rpi3.dts
  src/plat/exynos5/overlay-exynos5250.dts
  src/plat/exynos5/overlay-exynos5410.dts
  src/plat/exynos5/overlay-exynos5422.dts
  src/plat/fvp/overlay-fvp.dts
  src/plat/hikey/overlay-hikey.dts
  src/plat/imx7/overlay-imx7sabre.dts
  src/plat/imx8m-evk/overlay-imx8mm-evk.dts
  src/plat/imx8m-evk/overlay-imx8mq-evk.dts
  src/plat/maaxboard/overlay-maaxboard.dts
  src/plat/odroidc2/overlay-odroidc2.dts
  src/plat/odroidc4/overlay-odroidc4.dts
  src/plat/qemu-arm-virt/overlay-qemu-arm-virt.dts
  src/plat/quartz64/overlay-quartz64.dts
  src/plat/rockpro64/overlay-rockpro64.dts
  src/plat/tk1/overlay-tk1.dts
  src/plat/tqma8xqp1gb/overlay-tqma8xqp1gb.dts
  src/plat/tx1/overlay-tx1.dts
  src/plat/tx2/overlay-tx2.dts
  src/plat/zynqmp/overlay-zynqmp.dts
Labels: hw-build, hw-test

#1208 Fix DDR region for Odroid-C4
  tools/dts/odroidc4.dts
Labels: hw-test
