Repository seL4/seL4, pull requests merged in 2024-07, with the labels that each got.

#1282 vspace: check for stale mapping on all flush types
  src/arch/arm/64/kernel/vspace.c
Labels: bug

#1284 manual: document useful constants for SC creation
  manual/parts/objects.tex
Labels: docs

#1290 configs: add zynqmp and rpi4 to verified platforms
  CAVEATS.md
  CHANGES.md
  configs/AARCH64_bcm2711_verified.cmake
  configs/AARCH64_zynqmp_verified.cmake
Labels: verification

#1292 bump autopep8 version
  tools/python-deps/setup.py
Labels: build-system

#1294 sel4-deps: tighten deps; update instructions
  tools/python-deps/setup.py
Labels: build-system

#1296 mcs: refactor awaken
  include/object/tcb.h
  src/kernel/thread.c
  src/object/tcb.c
Labels: MCS

#1298 mcs: remove parameter from schedContext_unbindTCB
  include/object/schedcontext.h
  src/object/objecttype.c
  src/object/schedcontext.c
  src/object/tcb.c
Labels: MCS, hw-test

#1235 QEMU: ensure output folder exists
  src/plat/qemu-arm-virt/config.cmake
  src/plat/qemu-riscv-virt/config.cmake
Labels: build-system

#1300 mcs: use local variable in postpone
  src/kernel/thread.c
Labels: MCS
