Repository seL4/seL4, pull requests merged in 2024-03, with the labels that each got.

#1211 style: fix cmake formatting spec
  .cmake-format.yaml
Labels: cleanup

#1221 RISC-V SMP: Fix Compile Error
  include/arch/riscv/arch/model/smp.h
Labels: SMP, hw-build, hw-test

#1219 Manual: Xinclude support
  libsel4/tools/syscall_stub_gen.py
  manual/tools/gen_invocations.py
Labels: docs

#1143 Add glossary to manual
  .gitignore
  include/machine/interrupt.h
  libsel4/include/sel4/syscalls.h
  manual/Makefile
  manual/manual.tex
  manual/parts/glossary.tex
  manual/parts/io.tex
Labels: docs

#1217 RISC-V: make trap_entry a function
  include/arch/riscv/arch/kernel/traps.h
  src/arch/riscv/kernel/boot.c
  src/arch/riscv/traps.S
Labels: hw-test

#1229 github: add AARCH64 C proof session
  .github/workflows/proof.yml
Labels: CI

#1194 CI: cancel older concurrent PR runs
  .github/workflows/compilation-checks.yml
Labels: CI
