Repository seL4/seL4, pull requests merged in 2025-03, with the labels that each got.

#759 RISC-V: reserve memory for SBI in device tree
  include/arch/riscv/arch/32/mode/hardware.h
  include/arch/riscv/arch/64/mode/hardware.h
  src/arch/riscv/kernel/vspace.c
  src/plat/ariane/overlay-ariane.dts
  src/plat/cheshire/overlay-cheshire.dts
  src/plat/hifive/overlay-hifive.dts
  src/plat/polarfire/overlay-polarfire.dts
  src/plat/qemu-riscv-virt/overlay-qemu-riscv-virt.dts
  src/plat/rocketchip/overlay-rocketchip-base.dts
  src/plat/rocketchip/overlay-rocketchip-zcu102.dts
  src/plat/spike/overlay-spike.dts
  src/plat/star64/overlay-star64.dts
  tools/hardware/config.py
  tools/hardware/utils/memory.py
Labels: verification, hw-build, hw-test

#914 boot: Check that predicted page tables were used
  src/kernel/boot.c
Labels: hw-build, hw-test

#1418 mcs: rephrase setNextInterrupt to ease verification
  src/kernel/thread.c
Labels: verification, MCS

#1382 statedata: only define tlbLockCount for cortex-a8
  include/arch/arm/arch/32/mode/model/statedata.h
  include/model/statedata.h
  src/arch/arm/32/model/statedata.c
  src/arch/arm/armv/armv7-a/tlb.c
  src/arch/arm/config.cmake
  src/model/statedata.c
Labels: cleanup, hw-build

#1426 tools: fix kernel physBase alignment on AArch64
  tools/hardware/config.py
Labels: hw-build, hw-test

#1423 mcs: rephrase invokeSchedControl_ConfigureFlags
  src/object/schedcontrol.c
Labels: verification, MCS

#1429 mcs: some small changes to ease verification
  include/kernel/faulthandler.h
  src/api/syscall.c
  src/kernel/faulthandler.c
  src/kernel/thread.c
Labels: MCS

#1434 Add missing userError for VSpace invocation
  src/arch/arm/64/kernel/vspace.c
Labels: proof-test

#1430 utils: wrap config_set for verification
  include/util.h
Labels: verification
