Repository seL4/seL4, pull requests merged in 2025-02, with the labels that each got.

#1354 Platform support for Cheshire (Digilent Genesys2)
  include/drivers/irq/riscv_plic0.h
  libsel4/sel4_plat_include/cheshire/sel4/plat/api/constants.h
  src/plat/cheshire/config.cmake
  src/plat/cheshire/overlay-cheshire.dts
  tools/dts/cheshire.dts
  tools/hardware.yml
Labels: new-platform

#1372 aarch64: fix building with clang-18
  include/arch/arm/arch/64/mode/machine/fpu.h
Labels: hw-build, build-system

#1375 riscv: traps coming from s-mode should not be treated as a u-mode trap
  src/arch/riscv/c_traps.c
Labels: debug-build

#1390 platform_gen: only generate regions that are actually used
  config.cmake
  tools/hardware/outputs/c_header.py
  tools/hardware/outputs/compat_strings.py
  tools/hardware/outputs/elfloader.py
  tools/hardware/outputs/json.py
  tools/hardware/outputs/yaml.py
  tools/hardware_gen.py
Labels: build-system

#1297 thread state: abandon replyObject NULL invariant
  include/fastpath/fastpath.h
  include/object/reply.h
  src/fastpath/fastpath.c
  src/kernel/thread.c
  src/object/endpoint.c
  src/object/reply.c
Labels: MCS

#1358 Fix apparent potential bug in `cancelIPC` for MCS
  src/object/endpoint.c
Labels: verification, MCS

#1405 riscv: rename incorrect level2_pt -> level1_pt
  include/arch/riscv/arch/model/statedata.h
  src/arch/riscv/kernel/vspace.c
  src/arch/riscv/model/statedata.c
Labels: hw-build

#1337 arm,gic_v3: consolidate types for verification
  include/arch/arm/arch/machine/gic_v3.h
  src/arch/arm/machine/gic_v3.c
Labels: verification, virtualisation

#1408 Ignore clang 20 warning that breaks the build
  CMakeLists.txt
Labels: build-system
